/**
 * Sound model representing a sound in the library
 * Maps to the 'sounds' table in the database
 */
class Sound {
  constructor(id, userId, name, type, filepath, url, configJson, fileSize, duration, createdAt, updatedAt) {
    this.id = id;
    this.userId = userId;
    this.name = name;
    this.type = type;
    this.filepath = filepath;
    this.url = url;
    this.configJson = configJson;
    this.fileSize = fileSize;
    this.duration = duration;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Create Sound from database row (snake_case)
   * @param {Object} row - Database row
   * @returns {Sound}
   */
  static fromRow(row) {
    return new Sound(
      row.id,
      row.user_id,
      row.name,
      row.type,
      row.filepath || row.file_path,  // Support both variations
      row.url,
      row.config_json,
      row.file_size,
      row.duration,
      row.created_at,
      row.updated_at
    );
  }

  /**
   * Create Sound from JSON object (camelCase)
   * @param {Object} json - JSON object
   * @returns {Sound}
   */
  static fromJSON(json) {
    return new Sound(
      json.id,
      json.userId || json.user_id,
      json.name,
      json.type,
      json.filepath || json.filePath,
      json.url,
      json.config || json.configJson,
      json.fileSize,
      json.duration,
      json.createdAt,
      json.updatedAt
    );
  }

  /**
   * Convert to database row format (snake_case)
   * @returns {Object}
   */
  toRow() {
    return {
      id: this.id,
      user_id: this.userId,
      name: this.name,
      type: this.type,
      file_path: this.filepath,  // Use consistent snake_case for DB
      url: this.url,
      config_json: this.configJson,
      file_size: this.fileSize,
      duration: this.duration,
      created_at: this.createdAt,
      updated_at: this.updatedAt
    };
  }

  /**
   * Convert to JSON object (camelCase)
   * @returns {Object}
   */
  toJSON() {
    return {
      id: this.id,
      userId: this.userId,
      name: this.name,
      type: this.type,
      filepath: this.filepath,
      url: this.url,
      config: this.configJson,
      fileSize: this.fileSize,
      duration: this.duration,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    };
  }

  /**
   * Convert model instance to API response format
   * @returns {Object} Data in API response format
   */
  toApiFormat() {
    const result = {
      id: this.id,
      name: this.name,
      soundType: this.type,
      source: {
        type: this.type
      },
      config: this.configJson,
      createdAt: this.createdAt ? new Date(this.createdAt).getTime() : null
    };

    // Add type-specific source properties
    if (this.type === 'file' && this.filepath) {
      result.source.url = this.filepath;
      if (this.fileSize) result.source.fileSize = this.fileSize;
      if (this.duration) result.source.duration = this.duration;
    } else if ((this.type === 'url' || this.type === 'stream') && this.url) {
      result.source.url = this.url;
    } else if (this.configJson) {
      // For oscillator, noise, etc., config contains parameters
      Object.assign(result.source, this.configJson);
    }

    return result;
  }

  /**
   * Create a new Sound instance from API request data
   * @param {Object} requestData - Request body from API
   * @param {string} userId - Owner of the sound
   * @returns {Sound} New Sound instance
   */
  static fromApiRequest(requestData, userId) {
    const now = new Date();
    return new Sound(
      null, // Will be generated by DB
      userId,
      requestData.name,
      requestData.type || 'file',
      requestData.source?.url && requestData.source.type === 'file' ? requestData.source.url : null,
      requestData.source?.url && requestData.source.type !== 'file' ? requestData.source.url : null,
      requestData.config || {},
      requestData.source?.fileSize || null,
      requestData.source?.duration || null,
      now,
      now
    );
  }
}

module.exports = Sound;